name: VERCEL DEPLOY

on: workflow_dispatch
jobs:
  vercel-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        architecture: [x64]
    steps:
      - name: Check out Git Repository
        uses: actions/checkout@v3

      - name: RUN DEPLOY [VERCEL]
        uses: amondnet/vercel-action@v20
        with:
          working-directory: frontend
          vercel-args: '--prod'
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
