name: WORKFLOW CONTROLLER

on: [workflow_dispatch, pull_request]

jobs:
  frontend:
    uses: ./.github/workflows/frontend-test.yml
  backend:
    needs: frontend
    uses: ./.github/workflows/backend-test.yml
  deploy:
    if: ${{ github.event.pull_request == 'closed' }}
    needs: backend
    uses: ./.github/workflows/vercel-deploy.yml
